### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by ButyAfter** [FusionBrainLab/HairFastGAN#11]
(python39)>python .\main.py --face_path=6.png --shape_path=7.png --color_path=8.png --input_dir=input --result_path=output/result.png

No CUDA runtime is found, using CUDA_HOME='C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8'
E:\CXY\Environment\anaconda3\envs\python39\lib\site-packages\torch\utils\cpp_extension.py:358: UserWarning: Error checking compiler version for cl: [WinError 2] 系统
找不到指定的文件。
  warnings.warn(f'Error checking compiler version for {compiler}: {error}')
Traceback (most recent call last):

IndexError: list index out of range

**Comment by maximkm** [comment]
Hello, it appears to be caused by an incorrect environment setup. Judging by your error, you are using Windows and also python 3.9.

I suggest you install [WSL](https://learn.microsoft.com/en-us/windows/wsl/install), and use poetry to install all dependencies on python 3.10, just like the instructions in the [README](https://github.com/AIRI-Institute/HairFastGAN/blob/main/README.md#installation). This should fix all the errors.
