### ISSUE TITLE
feature: Is there a way to do a hair replacement while keeping the original picture?

### ISSUE THREAD

**Issue by zmzimpl** [FusionBrainLab/HairFastGAN#12]
The existing function needs to be cropped before I can replace the hairstyle, I would like to ask if there is a way to replace the hairstyle directly on the original image. 

I'm not a developer in AI, or you can tell me where to focus my changes and I'll try to change it.

Thanks for providing such a great project.

**Comment by maximkm** [comment]
Hello, since we are working in StyleGAN space, we need to crop images. At the same time, the StyleGAN cropper, can perform non-reversible transformations. The best thing to do is to try to paste the new image in the place where the old one was, but that will most likely not work well.

In a future version of our work, we will think about how to do the transformation on the original image.
