### ISSUE TITLE
Support for macOS with M1

### ISSUE THREAD

**Issue by paulocoutinhox** [FusionBrainLab/HairFastGAN#16]
Hi,

Can you add support for macOS with M1?

Thanks.

**Comment by maximkm** [comment]
Thank you for your interest in our project and for requesting macOS M1 support. We appreciate your enthusiasm.

Unfortunately, we are currently unable to provide support for macOS with M1 chips. Our project relies on StyleGAN2, which uses CUDA extensions. These extensions are compiled during the execution of our method using the Ninja build system, but since CUDA is not supported on macOS—especially on Apple Silicon (M1/M2) due to the absence of NVIDIA GPUs—this process is not feasible.

However, we can suggest two alternatives to work around this limitation:

1. **Use a virtual machine running Linux**: This option allows you to run the project in an environment where CUDA is supported.
2. **Utilize Docker on a machine with an NVIDIA GPU**: While Docker on macOS M1/M2 cannot support CUDA, running Docker on a host with an NVIDIA GPU would work.

We understand this may not be the ideal solution for your needs, but we're committed to improving platform compatibility in future updates. If you have any questions about these workarounds or need further clarification, please don't hesitate to ask.

**Comment by paulocoutinhox** [comment]
Hi, very thanks for your concise and complete answer.
