### ISSUE TITLE
How to use my images to train a model?

### ISSUE THREAD

**Issue by zihyunjudy** [FusionBrainLab/HairFastGAN#17]
I want to use this methodology on my study.
My images is already extract from video. (Every frame in the video)
But when I put my image in source photo and shape photo, I cannot get a good result.
The hair area will be vague. I guess maybe train my own model will be better?

**Comment by sahilshukla3003** [comment]
same question regarding training , how we can train this model on our images ?

**Comment by maximkm** [comment]
Thank you for your questions about using and potentially training the model with your own images.

Regarding image quality issues:
- Ensure all input images are properly cropped. This is crucial for good results. For more details on cropping, please see: https://github.com/AIRI-Institute/HairFastGAN/issues/3
- If you're experiencing blurry hair shapes, it's important to note that training your own encoders may not necessarily help, as the hair transfer process is primarily algorithmic rather than neural-based.

However, if you still want to try training:
1. You can train the Color encoder to improve color transfer.
2. You can also train the Refinement encoder to restore detail and perform inpainting.

Steps for training:
1. Generate a dataset using either `scripts/blending_gen.py` or `scripts/pp_gen.py`.
   - These scripts take arguments for dataset path, size, etc. Use `--help` for details.
2. Run the training with `scripts/blending_train.py` or `scripts/pp_train.py`.

I hope this information helps clarify the process. If you have any further questions or need additional assistance, please don't hesitate to ask.
