### ISSUE TITLE
Is it passible to apply in video hair swap?

### ISSUE THREAD

**Issue by seetimee** [FusionBrainLab/HairFastGAN#4]

**Comment by maximkm** [comment]
Hello, thank you for your question! Currently, our work does not support video processing. However, theoretically, our method could be adapted for use with video. But, it’s a more complex task that requires maintaining frame consistency, accounting for motion, and more. Due to these factors, the quality of our method might be poor in practice. We are actively working on improving the method to significantly enhance the quality and consistency of hair transfer. This should enable us to adapt our method to video in the foreseeable future.

**Comment by seetimee** [comment]
Thanks a lot for your excellent work
